// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: io.proto
#ifndef GRPC_io_2eproto__INCLUDED
#define GRPC_io_2eproto__INCLUDED

#include "io.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Io {

class Transfer final {
 public:
  static constexpr char const* service_full_name() {
    return "Io.Transfer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::Io::Chunk>> Receive(::grpc::ClientContext* context, const ::Io::Info& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::Io::Chunk>>(ReceiveRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::Io::Chunk>> AsyncReceive(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::Io::Chunk>>(AsyncReceiveRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::Io::Chunk>> PrepareAsyncReceive(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::Io::Chunk>>(PrepareAsyncReceiveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::Io::Packet>> Send(::grpc::ClientContext* context, ::Io::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::Io::Packet>>(SendRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Io::Packet>> AsyncSend(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Io::Packet>>(AsyncSendRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Io::Packet>> PrepareAsyncSend(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::Io::Packet>>(PrepareAsyncSendRaw(context, response, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Receive(::grpc::ClientContext* context, ::Io::Info* request, ::grpc::ClientReadReactor< ::Io::Chunk>* reactor) = 0;
      #else
      virtual void Receive(::grpc::ClientContext* context, ::Io::Info* request, ::grpc::experimental::ClientReadReactor< ::Io::Chunk>* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Send(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::ClientWriteReactor< ::Io::Packet>* reactor) = 0;
      #else
      virtual void Send(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::experimental::ClientWriteReactor< ::Io::Packet>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::Io::Chunk>* ReceiveRaw(::grpc::ClientContext* context, const ::Io::Info& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::Io::Chunk>* AsyncReceiveRaw(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::Io::Chunk>* PrepareAsyncReceiveRaw(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::Io::Packet>* SendRaw(::grpc::ClientContext* context, ::Io::Status* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::Io::Packet>* AsyncSendRaw(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::Io::Packet>* PrepareAsyncSendRaw(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::Io::Chunk>> Receive(::grpc::ClientContext* context, const ::Io::Info& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::Io::Chunk>>(ReceiveRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::Io::Chunk>> AsyncReceive(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::Io::Chunk>>(AsyncReceiveRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::Io::Chunk>> PrepareAsyncReceive(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::Io::Chunk>>(PrepareAsyncReceiveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::Io::Packet>> Send(::grpc::ClientContext* context, ::Io::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::Io::Packet>>(SendRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::Io::Packet>> AsyncSend(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::Io::Packet>>(AsyncSendRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::Io::Packet>> PrepareAsyncSend(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::Io::Packet>>(PrepareAsyncSendRaw(context, response, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Receive(::grpc::ClientContext* context, ::Io::Info* request, ::grpc::ClientReadReactor< ::Io::Chunk>* reactor) override;
      #else
      void Receive(::grpc::ClientContext* context, ::Io::Info* request, ::grpc::experimental::ClientReadReactor< ::Io::Chunk>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Send(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::ClientWriteReactor< ::Io::Packet>* reactor) override;
      #else
      void Send(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::experimental::ClientWriteReactor< ::Io::Packet>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::Io::Chunk>* ReceiveRaw(::grpc::ClientContext* context, const ::Io::Info& request) override;
    ::grpc::ClientAsyncReader< ::Io::Chunk>* AsyncReceiveRaw(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::Io::Chunk>* PrepareAsyncReceiveRaw(::grpc::ClientContext* context, const ::Io::Info& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::Io::Packet>* SendRaw(::grpc::ClientContext* context, ::Io::Status* response) override;
    ::grpc::ClientAsyncWriter< ::Io::Packet>* AsyncSendRaw(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::Io::Packet>* PrepareAsyncSendRaw(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Receive_;
    const ::grpc::internal::RpcMethod rpcmethod_Send_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Receive(::grpc::ServerContext* context, const ::Io::Info* request, ::grpc::ServerWriter< ::Io::Chunk>* writer);
    virtual ::grpc::Status Send(::grpc::ServerContext* context, ::grpc::ServerReader< ::Io::Packet>* reader, ::Io::Status* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Receive() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Receive(::grpc::ServerContext* /*context*/, const ::Io::Info* /*request*/, ::grpc::ServerWriter< ::Io::Chunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReceive(::grpc::ServerContext* context, ::Io::Info* request, ::grpc::ServerAsyncWriter< ::Io::Chunk>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Send : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Send() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Send() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Send(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Io::Packet>* /*reader*/, ::Io::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSend(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::Io::Status, ::Io::Packet>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Receive<WithAsyncMethod_Send<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Receive() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::Io::Info, ::Io::Chunk>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::Io::Info* request) { return this->Receive(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_Receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Receive(::grpc::ServerContext* /*context*/, const ::Io::Info* /*request*/, ::grpc::ServerWriter< ::Io::Chunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::Io::Chunk>* Receive(
      ::grpc::CallbackServerContext* /*context*/, const ::Io::Info* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::Io::Chunk>* Receive(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::Io::Info* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Send : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Send() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::Io::Packet, ::Io::Status>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::Io::Status* response) { return this->Send(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_Send() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Send(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Io::Packet>* /*reader*/, ::Io::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::Io::Packet>* Send(
      ::grpc::CallbackServerContext* /*context*/, ::Io::Status* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::Io::Packet>* Send(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::Io::Status* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Receive<ExperimentalWithCallbackMethod_Send<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Receive<ExperimentalWithCallbackMethod_Send<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Receive() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Receive(::grpc::ServerContext* /*context*/, const ::Io::Info* /*request*/, ::grpc::ServerWriter< ::Io::Chunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Send : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Send() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Send() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Send(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Io::Packet>* /*reader*/, ::Io::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Receive() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Receive(::grpc::ServerContext* /*context*/, const ::Io::Info* /*request*/, ::grpc::ServerWriter< ::Io::Chunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReceive(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Send : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Send() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Send() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Send(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Io::Packet>* /*reader*/, ::Io::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSend(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Receive() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->Receive(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_Receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Receive(::grpc::ServerContext* /*context*/, const ::Io::Info* /*request*/, ::grpc::ServerWriter< ::Io::Chunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Receive(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* Receive(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Send : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Send() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->Send(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Send() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Send(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::Io::Packet>* /*reader*/, ::Io::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* Send(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* Send(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Receive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Receive() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::Io::Info, ::Io::Chunk>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::Io::Info, ::Io::Chunk>* streamer) {
                       return this->StreamedReceive(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Receive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Receive(::grpc::ServerContext* /*context*/, const ::Io::Info* /*request*/, ::grpc::ServerWriter< ::Io::Chunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedReceive(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::Io::Info,::Io::Chunk>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Receive<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Receive<Service > StreamedService;
};

}  // namespace Io


#endif  // GRPC_io_2eproto__INCLUDED
