// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: io.proto

#include "io.pb.h"
#include "io.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Io {

static const char* FilesTransfer_method_names[] = {
  "/Io.FilesTransfer/Download",
  "/Io.FilesTransfer/Upload",
};

std::unique_ptr< FilesTransfer::Stub> FilesTransfer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FilesTransfer::Stub> stub(new FilesTransfer::Stub(channel));
  return stub;
}

FilesTransfer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Download_(FilesTransfer_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Upload_(FilesTransfer_method_names[1], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientReader< ::Io::Chunk>* FilesTransfer::Stub::DownloadRaw(::grpc::ClientContext* context, const ::Io::FileInfo& request) {
  return ::grpc::internal::ClientReaderFactory< ::Io::Chunk>::Create(channel_.get(), rpcmethod_Download_, context, request);
}

void FilesTransfer::Stub::experimental_async::Download(::grpc::ClientContext* context, ::Io::FileInfo* request, ::grpc::experimental::ClientReadReactor< ::Io::Chunk>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::Io::Chunk>::Create(stub_->channel_.get(), stub_->rpcmethod_Download_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::Io::Chunk>* FilesTransfer::Stub::AsyncDownloadRaw(::grpc::ClientContext* context, const ::Io::FileInfo& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::Io::Chunk>::Create(channel_.get(), cq, rpcmethod_Download_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::Io::Chunk>* FilesTransfer::Stub::PrepareAsyncDownloadRaw(::grpc::ClientContext* context, const ::Io::FileInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::Io::Chunk>::Create(channel_.get(), cq, rpcmethod_Download_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::Io::Packet>* FilesTransfer::Stub::UploadRaw(::grpc::ClientContext* context, ::Io::Status* response) {
  return ::grpc::internal::ClientWriterFactory< ::Io::Packet>::Create(channel_.get(), rpcmethod_Upload_, context, response);
}

void FilesTransfer::Stub::experimental_async::Upload(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::experimental::ClientWriteReactor< ::Io::Packet>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::Io::Packet>::Create(stub_->channel_.get(), stub_->rpcmethod_Upload_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::Io::Packet>* FilesTransfer::Stub::AsyncUploadRaw(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::Io::Packet>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::Io::Packet>* FilesTransfer::Stub::PrepareAsyncUploadRaw(::grpc::ClientContext* context, ::Io::Status* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::Io::Packet>::Create(channel_.get(), cq, rpcmethod_Upload_, context, response, false, nullptr);
}

FilesTransfer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FilesTransfer_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FilesTransfer::Service, ::Io::FileInfo, ::Io::Chunk>(
          [](FilesTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Io::FileInfo* req,
             ::grpc::ServerWriter<::Io::Chunk>* writer) {
               return service->Download(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FilesTransfer_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FilesTransfer::Service, ::Io::Packet, ::Io::Status>(
          [](FilesTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::Io::Packet>* reader,
             ::Io::Status* resp) {
               return service->Upload(ctx, reader, resp);
             }, this)));
}

FilesTransfer::Service::~Service() {
}

::grpc::Status FilesTransfer::Service::Download(::grpc::ServerContext* context, const ::Io::FileInfo* request, ::grpc::ServerWriter< ::Io::Chunk>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FilesTransfer::Service::Upload(::grpc::ServerContext* context, ::grpc::ServerReader< ::Io::Packet>* reader, ::Io::Status* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Io

